### ISSUE TITLE
Turn on with prior input selected, or allow a default input other than WiFi

### ISSUE THREAD

**Issue by arigit** [N0ciple/hass-kef-connector#1]
First, thanks for this integration! it's awesome to have support for this in HA.

I noticed that when turning  on the speakers from the HA media player card, the integration doesn't seem to be aware of what was the currently selected input and the speakers always turn on with WiFi preselected.

When manually turning on the speakers with the remote or with the touchscreen, the speakers always turn on with the previously-selected input.

Can the app offer the same behavior? or if that's not possible, can we have a configuration option to pre-select an input to be automatically setup at turn on, to somehow "get closer" to the expected behavior. I would think most users would normally use always the same fixed input (say HDMI or SPDIF) plus occasional wifi use with spotify or the like.

![image](https://user-images.githubusercontent.com/652673/143074999-5d4249b8-f726-4604-9900-cbdb015713a0.png)

**Comment by N0ciple** [comment]
Thanks for your feedback @arigit !
Actually when you press the on button, home assistant asks the speakers to turn on by setting their state to `powerOn`, as you can see [here](https://github.com/N0ciple/pykefcontrol/blob/a493321acf1942d73903cb7503ff3483f2870b08/pykefcontrol/kef_connector.py#L245). It seems that in the firmware, the `powerOn` state defaults to `wifi` regarding the source. I did not notice this behaviour before.
I will have a look to see if it is possible to track the "previous source" and turn the speakers on with the appropriate source. Bear in mind that if you reboot your home assistant instance, this info will be lost though !
If that is not possible, I will add an option to chose the default source when booting.

**Comment by N0ciple** [comment]
I have updated hass-kef-connector, now they keeps track of the last used source.
Update to version 0.5.4 to have this new feature !
