### ISSUE TITLE
Entity unavailable after HAOS 2022.3.0 udpate

### ISSUE THREAD

**Issue by tjxism** [N0ciple/hass-kef-connector#2]
Seems the plugin stopped working after HAOS 2022.3.0 udpate. The entity becomes unavailable and cannot pass configuration check: "Platform error media_player.kef_connector - Requirements for kef_connector not found: ['pykefcontrol==0.5']."

**Comment by N0ciple** [comment]
Thanks @tjxism, I just release version 0.5.5 which resolves the issue.
Update to the last version and you should be good. Feel free to reopen the issue if it is not the case !

**Comment by tjxism** [comment]
You're the best!
