### ISSUE TITLE
LSX II

### ISSUE THREAD

**Issue by gurmukhp** [N0ciple/hass-kef-connector#4]
Does this allow connecting to KEF LSX II via Home Assistant?

The official 'Kef' plugin only seems to support LSX.

Thanks!

**Comment by N0ciple** [comment]
Hello,

Yes it should support KEF LSX II "as is" although for the moment I did not implement specific code to detect the model. So `hass-kef-connector` would report that you have KEF LS50WII at the moment. It should work regardless of the model detected, although, you will not be able to switch to sources specific to your model such as USB.
I just finished my PhD so I'll have a bit more time to update `hass-kef-connector` in the near futur. :wink:

**Comment by N0ciple** [comment]
I don't think so.
The KEF LS50W and LSX v1 use a totally different local API that is not compatible with the "W2" platform that the LS60, LSX2 and LS50W2 are based on.
`hass-kef-connector ` have been developed to be compatible with the W2 platform, while the integration you mentioned is compatible with the previous platform.

**Comment by gurmukhp** [comment]
Super helpful, thank you!
